name: Run tests

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18'
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          args: --issues-exit-code=0

  unit:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18'
      - run: go test -v -cover ./...

#  acceptance:
#    name: Acceptance Tests (Terraform ${{ matrix.terraform-version }})
#    runs-on: ubuntu-latest
#    strategy:
#      fail-fast: false
#      matrix:
#        terraform-version:
#          - '1.0.*'
#          - '1.1.*'
#          - '1.2.*'
#    steps:
#      - uses: actions/checkout@v3
#      - uses: actions/setup-go@v3
#        with:
#          go-version: '1.18'
#      - uses: hashicorp/setup-terraform@v2
#        with:
#          terraform_version: ${{ matrix.terraform-version }}
#          terraform_wrapper: false
#      - run: go test -v -cover ./...
#        env:
#          TF_ACC: '1'